## These are overriden by GitHub
#safe:          true
#lsi:           false
#pygments:      true
#source:        your top-level directory

name:          Coding Standards & Style Guide
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://stanosmith.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
exclude:      [node_modules, Gruntfile.js, package.json]
